## Series
Trong Pandas, `Series` là mảng 1 chiều bao gồm một danh sách giá trị, và một mảng chứa index 
của các giá trị. Trong dữ liệu dảng bảng, mỗi Series được xem như là một cột của bảng đó. 
Cách đơn giản để tạo Series như sau

```python
s = pd.Series(data, index=None, name=None)
```

Trong đó `data` có thể  có dạng:

- dạng List của Python hoặc dạng `numpy.array`

- dictionary của Python

- là một hằng số duy nhất

`index` có thể truyền hoặc không, tùy vào dạng của `data` mà `index` sẽ được định nghĩa khác nhau. 
`name` là tên của `Series`, giá trị này cũng không nhất thiết phải truyền vào.

### Các cách khởi tạo

#### Khởi tạo Series bằng List hoặc dạng numpy.array {-}

Khi không truyền giá trị `index`, `Series` sẽ mặc định index của nó là 1 mảng số nguyên từ `0` đến `len(data) - 1` 

```python
pd.Series(data=[0, 1, 2], index=["a", "b", "c"], name="meow")
```

```{.python_output}
a    0
b    1
c    2
Name: meow, dtype: int64
```

#### Khởi tạo Series bằng dictionary {-}

```python
pd.Series({"b": 1, "a":0, "c": 2})
```

```{.python_output}
b    1
a    0
c    2
dtype: int64

```

```{block2, type='rmdnote'}
**_Lưu ý_:** 
Trong trường hợp bạn truyền biến `index` vào, `Series` sẽ đánh index dựa vào thứ tự trong `index`, và chỉ chứa các giá trị của dict có key nằm trong `index`. 
Với các giá trị trong biến `index` không có trong keys của dict, `Series` sẽ tạo ra các giá trị bị thiếu `NaN`.
```

```python
pd.Series({"a": 0, "b": 1, "c": 2, "e": 4}, index=["b", "c", "d", "a"])
```

```{.python_output} 
b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64
```

```{block2, type='rmdnote'}
**_Lưu ý_:** 
`NaN` là giá trị mặc định cho dữ liệu bị thiếu trong pandas và giá trị này có kiểu 
là `float64` nên kiểu dữ liệu của `Series` cũng là `float64` khác với `int64` ở ví dụ trước đó. 

```

#### Khởi tạo Series bằng một giá trị duy nhất {-}

```python
pd.Series(data=1, index=["a", "b", "c"])
```

```{.python_output} 
a    1
b    1
c    1
dtype: int64
```

### Một số thao tác cơ bản với Series

Thao tác trên `Series` cũng giống với thao tác trên `numpy.array`. Ngoài ra chúng ta còn có thể 
tác với Series dựa vào index

Ví dụ:

```python
s = pd.Series(data=[0, 1, 2, 3, 4, 5], index=["a", "b", "c", "d", "e", "f"])
```
#### Hiển thị toàn bộ giá trị của Series {-}

Để xem toàn bộ các giá trị của một Series, ta có thể gọi thuộc tính `.values`, kết quả sẽ trả về dạng `numpy.ndarray`


```python
s.values
```

```{.python_output}
array([0, 1, 2, 3, 4, 5])
```

#### Truy cập một phần tử trong Series {-}

- **Theo indice**

```python
s[2]
```

```{.python_output} 
2
``` 

- **Theo index**

```python
s["c"]
```

```{.python_output} 
2 
```
#### Lấy Series con của một Series {-}

- **Theo Slice indice**

```python
s[1:3]
```

```{.python_output}
b    1
d    2
dtype: int64
```

- **Theo Slice index**

```python
s["b":"c"]
```

```{.python_output} 
b    1
c    2
dtype: int64
``` 

- **Theo List indice**

```python
s[[1, 2, 4]]
```

```{.python_output}
b    1
c    2
e    4
dtype: int64
```

- **Theo List index**

```python
s[["b", "c", "e"]]
```

```{.python_output}
b    1
c    2
e    4
dtype: int64
```

- **Theo Điều kiện**

```python
s[s > s.mean()]
```

```{.python_output}
d    3
e    4
f    5
dtype: int64
```